### ISSUE TITLE
2w个汉字都写到数组里？是个狼人

### ISSUE THREAD

**Issue by leekbillow** [gitsher/pinyin#2]
现在能搜索到的汉字拼音首声母都是gbk的，看到这个支持utf8我震惊了，作者真狠啊，20000+汉字的数组，我服了。
我也没细看，直接使用了，结果提示changePinyinList和splitString是非静态方法不应该以静态方式调用，不知道是我调用有误还是什么问题，把这两个方法加上静态修饰符就不提示了

**Comment by gitsher** [comment]
> 现在能搜索到的汉字拼音首声母都是gbk的，看到这个支持utf8我震惊了，作者真狠啊，20000+汉字的数组，我服了。
> 我也没细看，直接使用了，结果提示changePinyinList和splitString是非静态方法不应该以静态方式调用，不知道是我调用有误还是什么问题，把这两个方法加上静态修饰符就不提示了

`In PHP 5, calling non-static methods statically generates an E_STRICT level warning.`

```
Warning
In PHP 7, calling non-static methods statically is deprecated, and will generate an E_DEPRECATED warning. Support for calling non-static methods statically may be removed in the future.
```

 确认在PHP高版本中会有相关提示，涉及到的两个方法已增加相关 static 修饰符。感谢 @bugithubUser 反馈！
